### ISSUE TITLE
Citação longa

### ISSUE THREAD

**Issue by joaopedrofn** [Gabrielr2508/template-tcc-latex-univasf#10]
Olá, existe uma forma correta de fazer citações longas nesse template? Grato. :)

**Comment by gab0gomes** [comment]
Oi, @joaopedrofn.

Acredito que não, mas vê se algo desse pacote te ajuda http://mirrors.ibiblio.org/CTAN/macros/latex/contrib/abntex2/doc/abntex2cite.pdf

E caso encontre algo interessante, abre um pull request! ;)

**Comment by joaopedrofn** [comment]
Achei o \begin{citacao} \end{citacao}, coloquei uma descriçãozinha la e fiz o pull request.
