### ISSUE TITLE
Remover os Exemplos

### ISSUE THREAD

**Issue by ruanmed** [Gabrielr2508/template-tcc-latex-univasf#12]
Sugiro a remoção da pasta de Exemplos do repositório e a criação de um repositório à parte contendo os TCC feitos pelos alunos, pois a mesma contém arquivos muito grandes e desnecessários para quem quiser clonar o repositório.

**Comment by gab0gomes** [comment]
Oi, @ruanmed. "Recomendar" é algo um pouco forte, acredito que você quis dizer "sugerir". Cuidado com a linguagem em ambientes open-source, você pode ser mal interpretado e ter suas propostas rejeitadas, principalmente em repositórios internacionais.

Sobre a sugestão, acho uma boa. Mas acredito que uma pasta na nuvem seja mais interessante nesse caso. Se puder, cria uma do caecom e manda um pull request removendo a pasta do repositório e colocando um link no readme para a pasta online.

Abraço!

**Comment by ruanmed** [comment]
Eita, haha, não me toquei na hora mesmo. Realmente a intenção foi de sugestão. Editei para transparecer isto.

Sobre disponibilizar um link na nuvem, seria uma pasta do Google Drive mesmo? E a melhor opção seria deixar ela pública para edição ou deixar somente com opção de visualização?

**Comment by gab0gomes** [comment]
Pode ser no Gdrive mesmo. Só visualização. Um dos motivos de ter deixado os arquivos aqui, é o fato de ser mais fácil de gerenciar as modificações e uploads de arquivos. Se uma pessoa quiser upar para o drive tem que passar por quem tem acesso à conta.

**Comment by gab0gomes** [comment]
Oi, @ruanmed. Alguma novidade?

**Comment by gab0gomes** [comment]
Estou fechando a issue por falta de atividade.

**Comment by ruanmed** [comment]
Opa @Gabrielr2508 , vou reabrir essa Issue pois pretendo ajeitar isso.

O que tu acha de um repositório no próprio GitHub com um README falando sobre os templates de TCC da Univasf e tal e falando que ali vão estar contidos os arquivos finais dos TCCs de alunos da Univasf elaborados utilizando LaTeX? 

Qual seria uma boa estrutura? Tenho em mente a seguinte:

Nome do repositório: tcc-alunos-univasf ou tcc-discentes-univasf ou somente tccs-univasf
.
+-- README.md
+-- CONTRIBUTING.md
+-- INDEX.md
+-- cecomp
|   +-- tcc-alunoX-do-cecomp.pdf
|   +-- tcc-alunoY-do-cecomp.pdf
+-- ${sigla-outro-colegiado}
|   +-- tcc-alunoX-do-${sigla-outro-colegiado}.pdf
|   +-- tcc-alunoY-do-${sigla-outro-colegiado}.pdf

O README.md seria o que eu disse acima, o CONTRIBUTING.md teria instruções para inserir seu TCC no repositório e o INDEX.md teria um índice com seções para cada colegiado, onde os TCCs fiquem listados por ano de depósito e título ou talvez por ano e nome do autor, contando um link direto para o arquivo PDF, claro haha.

**Comment by ruanmed** [comment]
Assim, esqueci de falar o que me motivou a retornar aqui, é que o projeto teoricamente pode ser importado no Overleaf diretamente, mas devido aos exemplos o source tá ficando com tamanho maior (mais de 88MB) que o máximo que o Overleaf permite (52.4MB).
Aí a pessoa que baixa o source repositório tem que remover manualmente os exemplos para conseguir importar no Overleaf.

Acho que inclusive poderíamos abrir mais um Issue sobre a inclusão de um guia para importar o projeto no Overleaf, pois é uma alternativa para quem não tem condições de instalar o LaTeX no computador que se tem acesso (tipo nos computadores do Laboratório de Computação de uso comum da Univasf).

**Comment by esron** [comment]
@ruanmed Outra solução interessante seria adicionar links para os repositórios dos trabalhos. 

Assim, o interessado pode ver não só o resultado final como também o código como exemplo.

**Comment by gab0gomes** [comment]
Acho válida a ideia da biblioteca. O meu questionamento é sobre a quantidade de trabalhos elaborados em LaTeX fora de computação. Tu acha que justifica isso? Acredito que pouca gente utilize a ferramenta nos outros cursos, pela complexidade e etc. Com exceção do pessoal que produz material didático com Fábio Henrique, nunca vi ninguém usando Talvez TCC's elaborados com qualquer ferramenta encaixe melhor, já que a proposta é manter apenas o PDF. Um outro ponto é pouca gente fora de computação vai buscar algo no GitHub, a maioria dos discentes desconhece a ferramenta.

Concordo com a retirada dos arquivos pdf's para um outro lugar de armazenamento como comentei acima. Acho que ficou mais fácil pelo fato da conta compartilhada do drive do Caecom. Sugiro deixar claro nas regras de contribuição como isso deve ser feito. Podendo, inclusive, abrir uma issue aqui solicitando a inclusão de um exemplo novo na pasta.

**Comment by ruanmed** [comment]
@esron , de fato pertinente, pois aí cada pessoa poderá ver coisas específicas que tenham no TCC de Fulano queira fazer no seu também, tipo uma tabela formatada de um jeito diferente, algum gráfico.

@Gabrielr2508 , sim, eu também acredito que quase ninguém deve utilizar. 

Então esse repositório de TCCs ficaria como TCCs elaborados com qualquer ferramenta? Seria interessante pq aí qualquer pessoa poderia expor o seu, caso queira (no caso, de fato deve ficar restrito à computação pois pessoas de outros cursos provavelmente não conhecem o GitHub haha).

Mas aí pontuo outra coisa, talvez para abranger todos os cursos deve ser melhor alguma ferramenta de gerenciamento de "publicações" da própria instituição que indexe os TCCs entregues e disponibilize online, que caso ainda não exista, deveria existir. 

Sugiro o seguinte então para esse repositório de TCCs: começar somente com os de computação feitos com LaTeX, e caso apareça demanda para incluir TCCs de outros cursos que então se avalie a pertinência de segmentar as pastas internas. O mesmo se aplicaria para caso apareçam TCCs de computação feitos com outras ferramentas.

Prossigo com a criação desse repositório? Se sim, só estou na dúvida de qual o melhor nome haha, no caso acho que preciso de um nome de título e um nome do "link".
Os nome dos links só pensei nos que falei acima, e agora mais um veio à mente: tccs-bib, ou tccs-latex-bib.

A descrição poderia ser Biblioteca de TCCs feitos em LaTeX por Alunos do Curso de Engenharia de Computação da Univasf.  E o título? :thinking:

**Comment by gab0gomes** [comment]
Acho `lib-tccs` um nome bom, já que vai estar dentro do Caecom.

O repositório poderia ser apenas o readme com os links para o drive, até pra facilitar a visualização.

**Comment by ruanmed** [comment]
Tá certo, vou criar com o nome `lib-tccs`. 

Agora sobre hospedar no Google Drive, eu achava uma boa ideia no princípio, mas houveram problemas recentes com pessoas movendo pastas/deletando pastas da pasta compartilhada do Google Drive do CAECOM, aí inclusive está sendo bolada pela gestão atual uma nova política de acesso a pasta e tal. 
O Google Drive não é muito prático para verificar histórico das coisas e retornar a versões anteriores, aí se acontecer de alguém deletar algum arquivo de lá (intencionalmente ou por engano) pode demorar bastante a ser descoberto que isso ocorreu, então acho melhor hospedar os PDFs no próprio repositório aqui no GitHub mesmo, e para incluir o seu bastará fazer um pull request seguinte o modelo.
